ReviewApp/reviewApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path('', include('reviews.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ReviewApp/reviews/urls.py
from django.urls import path
from . import views
from users import views as user_views
from .views import ProductListView, ProductDetailView 
#ReviewDetailView, ReviewCreateView, ReviewUpdateView, ReviewDeleteView

urlpatterns = [
	path('', views.home, name='reviews-home'),
	path('products/', ProductListView.as_view(), name='reviews-products'),
	path('products/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
	# path('reviews/<int:pk>', ReviewDetailView.as_view(), name='review-detail'),
	# path('reviews/add/', ReviewCreateView.as_view(), name='review-create'),
	# path('reviews/<int:pk>/update/', ReviewUpdateView.as_view(), name='review-update'),
	# path('reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review-delete'),
	path('about/', views.about, name='reviews-about'),
	path('contact/', views.contact, name='reviews-contact'),
	path('register/', user_views.register, name='register'),
	path('profile/', user_views.profile, name='profile'),
]

ReviewApp/reviews/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
	name = models.CharField(default ='', max_length = 255)
	brand = models.CharField(default = '', max_length = 255)
	avg_cost = models.DecimalField(default = 000.00, max_digits = 5, decimal_places = 2)
	category = models.CharField(default = '', max_length = 255)
	date_released = models.DateField(default = timezone.now)
	description = models.TextField()
	photo = models.ImageField(default = 'default.jpg', upload_to = 'product_pics')

	def __str__(self):
		return self.name


class Review(models.Model):
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	product = models.ForeignKey(Product, on_delete = models.CASCADE)
	rating = models.IntegerField(default = 0, max_length = 5)
	review_text = models.TextField()
	review_text = models.TextField()
	date = models.DateField(default = timezone.now)

	def __str__(self):
		return f'The Review of {self .product.name}'

ReviewApp/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')
	first_name = models.CharField(default ='', max_length = 30)
	last_name = models.CharField(default ='', max_length = 30)
	date_of_birth = models.DateField(default = timezone.now)
	address = models.CharField(default = '', max_length = 255)
	city = models.CharField(default = '', max_length = 100)
	country = models.CharField(default = '', max_length = 100)

	def __str__(self):
		return f'Profile for {self.user.username}'

ReviewApp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image', 'first_name', 'last_name', 'date_of_birth', 'address', 'city', 'country']			

ReviewApp/reviews/views.py
from django.shortcuts import render
from .models import Product
from django.views.generic import ListView, DetailView

# Create your views here.
def home(request):
	return render(request, 'reviews/home.html',{'title':'Home'})

def about(request):
	return render(request, 'reviews/about.html',{'title':'About'})

def contact(request):
	return render(request, 'reviews/contact.html',{'title':'Contact'})

class ProductListView(ListView):
	model = Product
	template_name = 'reviews/products.html'
	object_context_name = 'products'
	ordering = ['-name']

class ProductDetailView(DetailView):
	model = Product	

ReviewApp/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
	if request.method== 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account created for {username}!')
		return redirect('reviews-home')
	else:
		form = UserRegisterForm()
	return render(request, 'users/register.html' , {'form' :form})	

@login_required
def profile(request):
	u_form = UserUpdateForm()
	p_form = ProfileUpdateForm()

	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance = request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)

		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			message.success(request,f'the details of your account have been changed')

			return redirect('profile')

		if p_form.is_valid():
			p_form.save()
			message.success(requedt, f'the deatails of your account have been changed')

			return redirect('profile')

	else:
		u_form = UserUpdateForm(instance = request.user)
		p_form = ProfileUpdateForm(instance = request.user.profile)

	context = {
			'u_form': u_form,
			'p_form': p_form,
	}	
	return render(request, 'users/profile.html', context)

ReviewApp/reviews/templates/reviews/about.html
{% extends "reviews/base.html" %}
{% block content %}
<h1> About Us </h1>
{% endblock content %}

ReviewApp/reviews/templates/reviews/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% if title %}
<title> Review App - {{ title }} </title>
{% else %}
<title> Review App </title>
{%endif%}
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'reviews-home' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'reviews-about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'reviews-contact' %}">Contact Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'reviews-products' %}">Products</a>
      </li>
    </ul>

    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
      {% endif %}
  </div>
</nav>




  <div class="container py-4">
    <div class="row">
      <div class="col-md-8">
  {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <h3>Latest Reviews</h3>
      <ul class="list-group">
        <li class="list-group-item">Some Review</li>
      </ul>
    </div>
  </div>
</div>
</div>
<div></div>
  <footer class="footer">
    <div class="container">
      <small>&copy; Review App 2019</small>
    </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ReviewApp/reviews/templates/reviews/contact.html
{% extends "reviews/base.html" %}
{% block content %}
<h1> Contact Us </h1>
{% endblock content %}

ReviewApp/reviews/templates/reviews/home.html
{% extends "reviews/base.html" %}
{% block content %}
<h1> Home </h1>
<h2> Welcome to the App </h2>
<img src="https://images.unsplash.com/photo-1531297484001-80022131f5a1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1007&q=80"
class="w- 100">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec suscipit suscipit dolor eget scelerisque. Proin porttitor pharetra mauris ut sagittis. Praesent quis dignissim felis, id tincidunt massa. Fusce at sapien vulputate, suscipit enim id, ultrices arcu. In nec tellus in ex tempor lacinia. Donec sodales velit tortor, nec pretium lorem posuere eget. Phasellus vel leo vel massa interdum blandit. Nam ut sapien sed mauris varius tincidunt. Nulla vel dapibus lorem. Quisque suscipit ligula mauris, eget sollicitudin turpis fermentum vel. Ut ipsum arcu, auctor sit amet finibus eget, facilisis id eros. Quisque vulputate tristique pulvinar. Aliquam tellus ipsum, euismod nec ornare ac, porttitor eu turpis. Aliquam gravida turpis felis, et posuere augue hendrerit ac. Nulla facilisi. Vivamus et vestibulum turpis. </p>
{% endblock content %}

ReviewApp/reviews/templates/reviews/product_detail.html
{% extends "reviews/base.html" %}
{% block content %}
<h1>Product Details</h1>

<div>
		<img src="{{ object.photo.url }}" width="250"></div>
		<div class="col-md-9">
		<h2 class="product-name mb-O">{{ object.name }}</h2>
	<P>Brand: {{ product.brand }}</P>
	<p>Description: {{ product.description }}</p>
	<p>Category: {{ product.category }}</p>
	<p>Average Cost:{{ product.avg_cost }}</p>
	<p>Date Released: {{ product.date_released }}</p>
</div>

<h2> Product Reviews </h2>
	<div>
		{% for review in object.review_set.all %}
		{{ review }}
		<p>Author: {{ review.author }}</p>
		<p>Rating: {{ review.rating }}</p>
		<p>Review Text: {{ review.review_text }}</p>

		{% endfor %}
	</div>	

{% endblock content %}

ReviewApp/reviews/templates/reviews/products.html
{% extends "reviews/base.html" %}
{% block content %}
<h1> Products </h1>

{% for product in object_list %}

<div>
	
	<div class="col-md-9">
	<h3><a href="{% url 'product-detail' product.id %}">{{ product.name }}</a></h3>
	<h4 class="text-muted">{{ product.brand }}</h4>
</div>

{% endfor %}

{% endblock content %}

ReviewApp/users/templates/users/login.html
{% extends "reviews/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<fieldset class="form-group">
		<legend class="border-bottom mb-4">
			Review App - Login
		</legend>
	{{ form|crispy}}
	</fieldset>

	<div class='form-group'>
		<button class="btn btn-outline-info" type="submit">Login</button>
	</div>
</form>

<div class="border-top pt-3">
	<small class="text-muted">You need to create an account?<a class="ml-2" href="{% url 'register' %}">Register</a>
	</small>
</div>
{% endblock content %}		

ReviewApp/users/templates/users/profile.html
{% extends "reviews/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="profile">
		<div><img class="rounded-circle account-img" src="{{ user.profile.image.url }}"></div>
		<div class="profile.info">
			<h2>{{ user.profile }}</h2>
			<p class="text-secondary">{{ user.username }}</p>
			<p class="text-secondary">{{ user.email }}</p>
			<p class="text-secondary">{{ user.profile.full_name }}</p>
			<p class="text-secondary">{{ user.profile.address}}</p>
			<p class="text-secondary">{{ user.profile.city }}</p>
			<p class="text-secondary">{{ user.profile.country }}</p>
		</div>
	</div>
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Edit User Info</legend>
			{{ u_form|crispy }}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Update Info</button>
			</div>
		</form>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Edit Profile Info</legend>
				{{ p_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update Profile</button>
			</div>
		</form>
	{% endblock content %}		

ReviewApp/users/templates/users/register.html
{% extends "reviews/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<fieldset class="form-group">
		<legend class="border-bottom mb-4">
			Review App - Login
		</legend>
			{{ form|crispy}}
		</fieldset>
		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Register</button>
		</div>
	</form>
	<div class="border-top pt-3">
		<small class="text-muted">Are you already registered?<a class="ml-2" href="#">Login</a></small>
	</div>
{% endblock content %}						